- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/values.yaml
This PR allows to pass flags such as `--serve-artifacts` or `--artifacts-only` to `mlflow server`.
- fixes #
> [mlflow] Allow flags to be passed to `mlflow server`

- charts/drone/Chart.yaml
- charts/drone/values.yaml
- charts/kserve/Chart.yaml
- charts/kserve/templates/certificate.yaml
- charts/mlflow/Chart.yaml
- charts/mlflow/values.yaml
> [all charts] Change maintainer name to GitHub username.

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/service.yaml
- charts/mlflow/values.yaml
This enables us to e.g. set load balancer settings.
- fixes #
> [mlflow] Allow additional service resource annotations

- .github/workflows/release.yml
- charts/kserve/README.md
- charts/kserve/README.md.gotmpl
> [all charts] Enable skip existing chart functionality.

- charts/drone/Chart.yaml
- charts/drone/README.md
- charts/drone/unittests/runner_ingress_test.yaml
- charts/drone/unittests/server_ingress_test.yaml
> [drone] Add unit tests for drone server ingress.

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/README.md.gotmpl
- charts/mlflow/templates/configmap.yaml
- charts/mlflow/templates/job.yaml
- charts/mlflow/unittests/__snapshot__/configmap_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/ingress_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/secret_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/service_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/serviceaccount_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/servicemonitor_test.yaml.snap
- charts/mlflow/unittests/configmap_test.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/unittests/ingress_test.yaml
- charts/mlflow/unittests/job_test.yaml
- charts/mlflow/unittests/secret_test.yaml
- charts/mlflow/unittests/service_test.yaml
- charts/mlflow/unittests/serviceaccount_test.yaml
- charts/mlflow/unittests/servicemonitor_test.yaml
- charts/mlflow/values.yaml
> [mlflow]  Fix data migration problem and add unit tests

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.yaml
> [mlflow] Fix liveness and readiness probe problem from static prefix set

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.yaml
> [mlflow] Liveness Probe & Readiness Probe Improvements

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/templates/service.yaml
- charts/mlflow/templates/servicemonitor.yaml
- charts/mlflow/unittests/__snapshot__/servicemonitor_test.yaml.snap
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/unittests/service_test.yaml
- charts/mlflow/unittests/servicemonitor_test.yaml
- charts/mlflow/values.yaml
> [mlflow] Fix service monitor port number problem.

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/README.md.gotmpl
- charts/mlflow/files/dbchecker.sh
- charts/mlflow/templates/configmap.yaml
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/templates/job.yaml
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/job_test.yaml.snap
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/unittests/job_test.yaml
- charts/mlflow/values.yaml
Added an optional init container to both the deployment and migration job, which checks for the database availability. This is to make sure the database is available before starting the mlflow or the migrations container.
- fixes no issue
> [mlflow] Added db checker init container

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.yaml
As described in [cli help](https://github.com/mlflow/mlflow/blob/d112aedbc3faa21a688ce1a3545a75008ff2c6bd/mlflow/cli.py#L368-L379), default value is dependent on other flags passed to server, so we should leave it to the server to work out correct combination. Note that when using default `values.yaml`, behavior does not change between master and this PR.
- fixes #
> [mlflow] Avoid hardcoding `--default-artifact-root`

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/README.md.gotmpl
- charts/mlflow/files/dbchecker.sh
- charts/mlflow/templates/configmap.yaml
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/templates/job.yaml
- charts/mlflow/templates/secret.yaml
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/job_test.yaml.snap
- charts/mlflow/unittests/configmap_test.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/unittests/job_test.yaml
- charts/mlflow/unittests/secret_test.yaml
- charts/mlflow/values.yaml
> [mlflow] MySQL Backend Store Support

- .github/workflows/release.yml
- charts/n8n/.helmignore
- charts/n8n/Chart.lock
- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/README.md.gotmpl
- charts/n8n/templates/configmap.yaml
- charts/n8n/templates/deployment-webhook.yaml
- charts/n8n/templates/deployment-worker.yaml
- charts/n8n/templates/deployment.yaml
- charts/n8n/templates/pdb.yaml
- charts/n8n/templates/secret.yaml
- charts/n8n/unittests/__snapshot__/configmap_test.yaml.snap
- charts/n8n/unittests/configmap_test.yaml
- charts/n8n/unittests/deployment-webhooks_test.yaml
- charts/n8n/unittests/deployment-worker_test.yaml
- charts/n8n/unittests/deployment_test.yaml
- charts/n8n/unittests/secret_test.yaml
- charts/n8n/values-kind.yaml
- charts/n8n/values.schema.json
- charts/n8n/values.yaml
Adds enterprise license and S3 binary storage support.
- fixes #
> [n8n] Add license and S3 support

- .github/workflows/release.yml
- charts/mlflow/Chart.lock
- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/README.md.gotmpl
- charts/mlflow/templates/_helpers.tpl
- charts/mlflow/templates/configmap.yaml
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/templates/secret.yaml
- charts/mlflow/unittests/__snapshot__/configmap_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/configmap_test.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/unittests/secret_test.yaml
- charts/mlflow/values-kind.yaml
- charts/mlflow/values.schema.json
- charts/mlflow/values.yaml
Add bitnami's postgresql chart as an optional dependency
- fixes #20 
- fixes #40
> [mlflow] Add bitnami's postgresql and mysql charts as optional dependencies, and support for existing database secret

- .github/configs/cr.yaml
- .github/workflows/release.yml
- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.schema.json
- charts/mlflow/values.yaml
> [mlflow] Fix wrong sqlite memory syntax

- charts/n8n/Chart.lock
- charts/n8n/Chart.yaml
- charts/n8n/README.md
Automated update for n8n chart to version 1.84.1 on 2025-03-24 21:34:33.
> [n8n] Update n8n chart to 1.84.1

- .github/workflows/release.yml
- charts/outline/.helmignore
- charts/outline/Chart.yaml
- charts/outline/README.md
- charts/outline/templates/deployment.yaml
- charts/outline/values-kind.yaml
- charts/outline/values.yaml
> [outline] Fix minio bucket length problem

- .github/workflows/release.yml
- charts/outline/Chart.yaml
- charts/outline/README.md
> [outline] Fix release pipeline problem

- .github/workflows/release.yml
- charts/cloudflared/.helmignore
- charts/cloudflared/Chart.yaml
- charts/cloudflared/README.md
- charts/cloudflared/README.md.gotmpl
> [cloudflared] Skip kind cluster based integration tests for cloudflared chart

- charts/actualbudget/Chart.yaml
- charts/actualbudget/README.md
- charts/actualbudget/README.md.gotmpl
- charts/actualbudget/templates/secret.yaml
- charts/actualbudget/unittests/secret_test.yaml
- charts/actualbudget/values.schema.json
- charts/actualbudget/values.yaml
We have a typo in the openid settings. New `discoveryUrl` field added and `dicovertUrl` field deprecated. Deprecated fields will be removed in next major version.
- fixes #90
> [actualbudget] Fix typo in openid settings

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/README.md.gotmpl
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.schema.json
- charts/mlflow/values.yaml
We move `sqlite path`, `default artifact root`, and `artifact destination` static definitions to values yaml file. This will decrease unnecessary duplicated `argument` and `flag` definitions.
- fixes #100
> [mlflow] Move static definitions to values yaml file

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/README.md.gotmpl
- charts/mlflow/unittests/deployment_test.yaml
Fix the documentation for default sqlite path usage
- fixes #100
> [mlflow] Fix the documentation for default sqlite path usage

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/README.md.gotmpl
- charts/n8n/templates/deployment-webhook.yaml
- charts/n8n/templates/deployment-worker.yaml
- charts/n8n/templates/deployment.yaml
- charts/n8n/templates/secret.yaml
- charts/n8n/unittests/deployment-webhooks_test.yaml
- charts/n8n/unittests/deployment-worker_test.yaml
- charts/n8n/unittests/deployment_test.yaml
- charts/n8n/unittests/secret_test.yaml
- charts/n8n/values.schema.json
- charts/n8n/values.yaml
> [n8n] Add initial startup probe and external library support

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/README.md.gotmpl
- charts/n8n/templates/NOTES.txt
- charts/n8n/templates/deployment-webhook.yaml
- charts/n8n/templates/deployment-worker.yaml
- charts/n8n/templates/deployment.yaml
- charts/n8n/unittests/deployment-webhooks_test.yaml
- charts/n8n/unittests/deployment-worker_test.yaml
- charts/n8n/unittests/deployment_test.yaml
- charts/n8n/unittests/notes_test.yaml
- charts/n8n/values-kind.yaml
- charts/n8n/values.schema.json
- charts/n8n/values.yaml
- Move liveness probe and readiness probe to main, worker, and webhook blocks
- Add deprecation notices for root level volumes, volumeMounts, extraEnvVars, and extraSecretNamesForEnvFrom fields
- Add startup probe to worker and webhook blocks
- Add wait-for-main init container to worker and webhook blocks and make it configurable
- fixes #114
> [n8n] Chart Refactorings

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/README.md.gotmpl
- charts/n8n/templates/_helpers.tpl
- charts/n8n/templates/deployment-worker.yaml
- charts/n8n/templates/deployment.yaml
- charts/n8n/unittests/deployment-worker_test.yaml
- charts/n8n/unittests/deployment_test.yaml
- charts/n8n/values.schema.json
- charts/n8n/values.yaml
[Community Node](https://docs.n8n.io/integrations/community-nodes/installation/manual-install/#install-a-community-node) support. Chart users can start to install and use n8n community nodes.
- fixes #116
> [n8n] Add community node support

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/README.md.gotmpl
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/templates/secret.yaml
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.schema.json
- charts/mlflow/values.yaml
* Major change required actions documentation updated
* Service resource enable/disable flag added for service mesh cases
* Add extra pod labels to support systems like AKS workload identity
- fixes #129 
- fixes #130
> [mlflow] Add service enable flag and extra pod labels field

- charts/actualbudget/Chart.yaml
- charts/actualbudget/README.md
- charts/actualbudget/templates/deployment.yaml
- charts/actualbudget/unittests/deployment_test.yaml
- charts/actualbudget/values.schema.json
- charts/actualbudget/values.yaml
Mount sub path support for single file mounthing.
- fixes #
> [actualbudget] Persistence Sub Path Support

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/configmap.yaml
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/unittests/__snapshot__/configmap_test.yaml.snap
- charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap
- charts/mlflow/unittests/configmap_test.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values-kind.yaml
- charts/mlflow/values.schema.json
- charts/mlflow/values.yaml
Currently setting different log level to mlflow hard to apply because it needs several changes. We added another log configuration to set log level to all systems.
- fixes #137 
It looks like alembic doesn't care our log level configuration because it's statically defined in `/mlflow/.venv/lib/python3.13/site-packages/mlflow/store/db_migrations/alembic.ini` file. Currently, it looks like only way to change it from custom command but it's dangerous because path of file can easily change in the future.
> [mlflow] Log Level Settings

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/templates/deployment-worker.yaml
- charts/n8n/templates/deployment.yaml
- charts/n8n/unittests/deployment-worker_test.yaml
- charts/n8n/unittests/deployment_test.yaml
> [n8n] Fix npmRegistry without external packages usage

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/templates/ingress.yaml
- charts/n8n/unittests/__snapshot__/ingress_test.yaml.snap
- charts/n8n/unittests/ingress_test.yaml
Add ingress path for rest/oauth2-credential/callback
- fixes #141
> [n8n] OAuth2 Credentials Callback endpoint

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/templates/ingress.yaml
- charts/n8n/unittests/__snapshot__/ingress_test.yaml.snap
- charts/n8n/unittests/ingress_test.yaml
> [n8n] Ingress Static Files path

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/templates/deployment-worker.yaml
- charts/n8n/templates/deployment.yaml
- charts/n8n/templates/statefulset-worker.yaml
- charts/n8n/templates/statefulset.yaml
- charts/n8n/unittests/deployment-worker_test.yaml
- charts/n8n/unittests/deployment_test.yaml
- charts/n8n/unittests/statefulset-worker_test.yaml
- charts/n8n/unittests/statefulset_test.yaml
- charts/n8n/values.yaml
- When we set `main.persistence.volumeName` value, it sets to main pod volume names
- When we set `worker.persistence.volumeName` value, it sets to worker pod volume names
- fixes #154
> [n8n] Fix volume name when volumeName is set for main and worker pods

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/README.md.gotmpl
- charts/n8n/templates/_helpers.tpl
- charts/n8n/unittests/__snapshot__/deployment-worker_test.yaml.snap
- charts/n8n/unittests/__snapshot__/deployment_test.yaml.snap
- charts/n8n/unittests/__snapshot__/ingress_test.yaml.snap
- charts/n8n/unittests/__snapshot__/service_test.yaml.snap
- charts/n8n/unittests/__snapshot__/serviceaccount_test.yaml.snap
- charts/n8n/unittests/__snapshot__/servicemonitor_test.yaml.snap
- charts/n8n/unittests/__snapshot__/statefulset-worker_test.yaml.snap
- charts/n8n/unittests/__snapshot__/statefulset_test.yaml.snap
- charts/n8n/unittests/pdb_test.yaml
- charts/n8n/unittests/service_test.yaml
> Revert breaking selector label changes

- charts/outline/Chart.yaml
- charts/outline/README.md
- charts/outline/README.md.gotmpl
- charts/outline/templates/deployment.yaml
- charts/outline/unittests/deployment_test.yaml
> [outline] Fix wrong auth client secret environment variables

- charts/outline/Chart.yaml
- charts/outline/README.md
- charts/outline/README.md.gotmpl
- charts/outline/templates/deployment.yaml
- charts/outline/unittests/deployment_test.yaml
- charts/outline/values.schema.json
- charts/outline/values.yaml
> [outline] Fix external postgresql existing secret key field

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/templates/secret.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.schema.json
- charts/mlflow/values.yaml
> [mlflow] Add S3 existing secret support

- charts/cloudflared/Chart.yaml
- charts/cloudflared/README.md
- charts/cloudflared/README.md.gotmpl
- charts/cloudflared/templates/configmap.yaml
- charts/cloudflared/templates/deployment.yaml
- charts/cloudflared/templates/secret.yaml
- charts/cloudflared/unittests/configmap_test.yaml
- charts/cloudflared/unittests/deployment_test.yaml
- charts/cloudflared/values.schema.json
- charts/cloudflared/values.yaml
> [cloudflared] Add existing secret support for credentials json file and certificate pem file

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/templates/pvc.yaml
- charts/n8n/unittests/__snapshot__/deployment_test.yaml.snap
- charts/n8n/unittests/__snapshot__/pvc_test.yaml.snap
- charts/n8n/unittests/deployment_test.yaml
- charts/n8n/unittests/pvc_test.yaml
> [n8n] Add missing PVC case for multiple main nides and ReadWriteMany mode persistence

- charts/n8n/Chart.yaml
- charts/n8n/README.md
- charts/n8n/values.yaml
> [n8n] Add default bitnami redis port number

- charts/mlflow/Chart.yaml
- charts/mlflow/README.md
- charts/mlflow/templates/deployment.yaml
- charts/mlflow/unittests/deployment_test.yaml
- charts/mlflow/values.schema.json
- charts/mlflow/values.yaml
This PR replaces the busybox image with values which can be defined by the user - this is because they are currently hardcoded.
- fixes #
> [mlflow] Adding in additional values to support the use of different init images

- charts/outline/Chart.yaml
- charts/outline/README.md
- charts/outline/templates/deployment.yaml
- charts/outline/unittests/__snapshot__/deployment_test.yaml.snap
- charts/outline/unittests/deployment_test.yaml
This pull request addresses issue #238 by implementing an automatic restart mechanism for Kubernetes deployments when referenced ConfigMaps or Secrets are updated. The solution ensures that pods automatically pick up configuration changes without requiring manual intervention, improving the deployment workflow and reducing downtime caused by outdated configurations.
**Key Changes:**
- Checksum Annotations: Added logic to include checksum annotations in deployment templates, computed from the content of referenced ConfigMaps and Secrets.
- Change Detection: Implemented detection of ConfigMap/Secret content changes, triggering a rolling update when checksums differ.
- Seamless Integration: The solution works automatically without requiring additional configuration, ensuring ease of use. …
> [outline] Add Automatic Deployment Restart on ConfigMap/Secret Updates
