charts/outline/Chart.yaml, charts/outline/README.md, charts/outline/templates/secret.yaml, charts/outline/unittests/secret_test.yaml
Changes OIDC scopes parameter format from comma separated scopes to space separated scopes.
- fixes #77
=> [outlune] Fix wrong scopes format in OIDC scopes secret

charts/mlflow/Chart.lock, charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 2.21.1 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 2.21.1

charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 2.21.2 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 2.21.2

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.84.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.84.2

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.84.3 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.84.3

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.85.4 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.85.4

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md
This PR updates the cloudflared chart to use the latest image version 2025.4.0 from cloudflare/cloudflared. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [cloudflared] Update cloudflared chart to 2025.4.0

charts/mlflow/Chart.lock, charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 2.21.3 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 2.21.3

charts/actualbudget/Chart.yaml, charts/actualbudget/README.md
This PR updates the actualbudget chart to use the latest image version 25.4.0 from actualbudget/actual-server. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [actualbudget] Update actualbudget chart to 25.4.0

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.86.0 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.86.0

charts/outline/Chart.lock, charts/outline/Chart.yaml, charts/outline/README.md
This PR updates the outline chart to use the latest image version 0.83.0 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.83.0

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.88.0 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.88.0

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.89.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.89.2

charts/mlflow/Chart.lock, charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 2.22.0 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 2.22.0

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md
This PR updates the cloudflared chart to use the latest image version 2025.4.2 from cloudflare/cloudflared. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [cloudflared] Update cloudflared chart to 2025.4.2

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.90.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.90.2

charts/actualbudget/Chart.yaml, charts/actualbudget/README.md
This PR updates the actualbudget chart to use the latest image version 25.5.0 from actualbudget/actual-server. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [actualbudget] Update actualbudget chart to 25.5.0

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.91.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.91.2

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.91.3 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.91.3

charts/outline/Chart.lock, charts/outline/Chart.yaml, charts/outline/README.md
This PR updates the outline chart to use the latest image version 0.84.0 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.84.0

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md
This PR updates the cloudflared chart to use the latest image version 2025.5.0 from cloudflare/cloudflared. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [cloudflared] Update cloudflared chart to 2025.5.0

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.93.0 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.93.0

.github/workflows/release.yml, charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.95.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.95.2

charts/actualbudget/Chart.yaml, charts/actualbudget/README.md
This PR updates the actualbudget chart to use the latest image version 25.6.1 from actualbudget/actual-server. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [actualbudget] Update actualbudget chart to 25.6.1

charts/mlflow/Chart.lock, charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 2.22.1 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 2.22.1

charts/mlflow/Chart.yaml, charts/mlflow/README.md, charts/mlflow/unittests/__snapshot__/deployment_test.yaml.snap, charts/mlflow/unittests/deployment_test.yaml, charts/mlflow/values.yaml
Upstream docker image started to to non-root mlflow user. We can add [non-root user UID and GID](https://github.com/burakince/mlflow/tree/2.22.1?tab=readme-ov-file#security-context) to default pod and container security contexes.
- fixes #
=> [mlflow] Change default security context to non-root mlflow user

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md
This PR updates the cloudflared chart to use the latest image version 2025.6.0 from cloudflare/cloudflared. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [cloudflared] Update cloudflared chart to 2025.6.0

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.97.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.97.1

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.98.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.98.1

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md
This PR updates the cloudflared chart to use the latest image version 2025.6.1 from cloudflare/cloudflared. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [cloudflared] Update cloudflared chart to 2025.6.1

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.98.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.98.2

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.99.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.99.1

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.100.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.100.1

charts/actualbudget/Chart.yaml, charts/actualbudget/README.md
This PR updates the actualbudget chart to use the latest image version 25.7.0 from actualbudget/actual-server. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [actualbudget] Update actualbudget chart to 25.7.0

charts/actualbudget/Chart.yaml, charts/actualbudget/README.md
This PR updates the actualbudget chart to use the latest image version 25.7.1 from actualbudget/actual-server. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [actualbudget] Update actualbudget chart to 25.7.1

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md
This PR updates the cloudflared chart to use the latest image version 2025.7.0 from cloudflare/cloudflared. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [cloudflared] Update cloudflared chart to 2025.7.0

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.101.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.101.1

charts/outline/Chart.lock, charts/outline/Chart.yaml, charts/outline/README.md
This PR updates the outline chart to use the latest image version 0.85.1 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.85.1

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.102.4 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.102.4

charts/mlflow/Chart.lock, charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 3.1.3 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 3.1.3

charts/outline/Chart.yaml, charts/outline/README.md, charts/outline/README.md.gotmpl, charts/outline/templates/_helpers.tpl, charts/outline/unittests/deployment_test.yaml
The helm default command takes the default value as first parameter and the optional value as 2nd parameter.
This was used wrongly on 3 occasions. Therefore, it's not possible to use another port than the default one.
=> [outline] Fix external postgres port config

charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 3.1.4 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 3.1.4

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.104.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.104.1

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.104.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.104.2

charts/actualbudget/Chart.yaml, charts/actualbudget/README.md
This PR updates the actualbudget chart to use the latest image version 25.8.0 from actualbudget/actual-server. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [actualbudget] Update actualbudget chart to 25.8.0

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.105.3 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.105.3

charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 3.2.0 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 3.2.0

charts/outline/Chart.lock, charts/outline/Chart.yaml, charts/outline/README.md
This PR updates the outline chart to use the latest image version 0.86.0 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.86.0

charts/outline/Chart.lock, charts/outline/Chart.yaml, charts/outline/README.md
This PR updates the outline chart to use the latest image version 0.86.1 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.86.1

charts/pypiserver/Chart.yaml, charts/pypiserver/README.md
This PR updates the pypiserver chart to use the latest image version v2.4.0 from pypiserver/pypiserver. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [pypiserver] Update pypiserver chart to v2.4.0

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.107.3 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.107.3

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.107.4 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.107.4

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md
This PR updates the cloudflared chart to use the latest image version 2025.8.1 from cloudflare/cloudflared. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [cloudflared] Update cloudflared chart to 2025.8.1

charts/mlflow/Chart.lock, charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 3.3.1 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 3.3.1

charts/mlflow/Chart.lock, charts/mlflow/Chart.yaml, charts/mlflow/README.md
This PR updates the mlflow chart to use the latest image version 3.3.2 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 3.3.2

charts/outline/Chart.lock, charts/outline/Chart.yaml, charts/outline/README.md
This PR updates the outline chart to use the latest image version 0.87.1 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.87.1

charts/outline/Chart.yaml, charts/outline/README.md
This PR updates the outline chart to use the latest image version 0.87.3 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.87.3

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.109.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.109.1

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.109.2 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.109.2

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.110.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.110.1

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.111.0 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.111.0

charts/mlflow/Chart.yaml, charts/mlflow/README.md, charts/mlflow/values.yaml
This PR updates the mlflow chart to use the latest image version 3.4.0 from burakince/mlflow. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [mlflow] Update mlflow chart to 3.4.0

charts/outline/Chart.yaml, charts/outline/README.md, charts/outline/values.yaml
This PR updates the outline chart to use the latest image version 0.87.4 from outlinewiki/outline. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [outline] Update outline chart to 0.87.4

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.111.1 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.111.1

charts/cloudflared/Chart.yaml, charts/cloudflared/README.md, charts/cloudflared/templates/deployment.yaml, charts/cloudflared/unittests/__snapshot__/deployment_test.yaml.snap, charts/cloudflared/unittests/deployment_test.yaml, charts/cloudflared/values.yaml
Removes the `NET_RAW` capability from the default container `securityContext` to comply with PodSecurity "baseline:latest" policies.
- fixes #
=> [cloudflared] Remove NET_RAW capability from container securityContext

charts/actualbudget/Chart.yaml, charts/actualbudget/README.md
This PR updates the actualbudget chart to use the latest image version 25.10.0 from actualbudget/actual-server. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [actualbudget] Update actualbudget chart to 25.10.0

charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.113.3 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.113.3

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.114.3 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.114.3

charts/n8n/Chart.lock, charts/n8n/Chart.yaml, charts/n8n/README.md
This PR updates the n8n chart to use the latest image version 1.114.4 from n8nio/n8n. This ensures the chart stays current with the latest upstream release.
- fixes none
=> [n8n] Update n8n chart to 1.114.4
